-- yatai_votes テーブル作成スクリプト
-- Supabase SQL Editor や psql から実行してください。

create table if not exists public.yatai_votes (
  id bigint generated by default as identity primary key,
  booth_id text not null,
  taste integer not null check (taste between 1 and 5),
  service integer not null check (service between 1 and 5),
  visual integer not null check (visual between 1 and 5),
  amount integer not null check (amount between 1 and 5),
  comment text,
  timestamp timestamptz not null default timezone('utc', now())
);

-- Row Level Security を有効化
alter table public.yatai_votes enable row level security;

-- 既存ポリシーがあれば削除してから再作成
drop policy if exists "allow inserts from service role" on public.yatai_votes;
drop policy if exists "allow inserts from anon" on public.yatai_votes;

create policy "allow inserts from anon"
  on public.yatai_votes
  for insert
  to anon
  with check (true);
